{
 "title": "Airflow Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total DAG parsing time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_total_parse_time{}"
    }
   ]
  },
  {
   "title": "Dag bag size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_dagbag_size{}" }
   ]
  },
  {
   "title": "DAG import errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{}",
     "legendFormat": "import errors"
    }
   ]
  },
  {
   "title": "default_pool slots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_pool_open_slots_default_pool{}"
    }
   ]
  },
  {
   "title": "Parsing Processes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_processes{}"
    }
   ]
  },
  {
   "title": "Airflow Running/ Queued/ Starving Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Airflow Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Airflow Running Tasks" },
    {
     "expr": "airflow_scheduler_tasks_starving{}",
     "legendFormat": "Starving tasks"
    }
   ]
  }
 ]
}